# Generated by Django 4.2.6 on 2023-11-12 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="description",
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                choices=[
                    ("Суп", "Суп"),
                    ("Завтрак", "Завтрак"),
                    ("Выпечка", "Выпечка"),
                    ("Десерт", "Десерт"),
                    ("Фаст-фуд", "Фаст-фуд"),
                    ("Молочка", "Молочка"),
                    ("Салат", "Салат"),
                    ("Мясо", "Мясо"),
                ],
                max_length=50,
                verbose_name="Название категории",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="products",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="recipe",
            name="products",
            field=models.TextField(default="none"),
        ),
    ]
