# Generated by Django 4.2.6 on 2023-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(default=10),
        ),
    ]
